"use client";
import { FormEvent, useEffect, useState } from "react";

type Page = "dashboard"|"lr"|"booking"|"customers"|"fleet"|"tracking";
type Item = {id:number; type:string; title:string; route:string; customer:string; vehicle:string; status:string; amount:string};
const seed: Item[] = [
 {id:1,type:"booking",title:"STSL-2026-1048",route:"Pune → Nagpur",customer:"Rajlaxmi Industries",vehicle:"MH 12 AB 4589",status:"In Transit",amount:"₹24,500"},
 {id:2,type:"booking",title:"STSL-2026-1047",route:"Mumbai → Kolhapur",customer:"Mahalaxmi Traders",vehicle:"MH 04 JK 2210",status:"Delivered",amount:"₹18,200"},
 {id:3,type:"booking",title:"STSL-2026-1046",route:"Nashik → Pune",customer:"Sahyadri Foods",vehicle:"MH 15 CD 9090",status:"Booked",amount:"₹12,800"},
];
const nav:{id:Page;label:string;icon:string}[]=[{id:"dashboard",label:"Dashboard",icon:"▦"},{id:"lr",label:"LR Generation",icon:"▤"},{id:"booking",label:"Booking",icon:"＋"},{id:"customers",label:"Customers",icon:"♙"},{id:"fleet",label:"Drivers & Lorries",icon:"▰"},{id:"tracking",label:"LR Tracking",icon:"⌖"}];

export default function TransportApp({authenticatedName}:{authenticatedName:string|null}){
 const [login,setLogin]=useState(false),[page,setPage]=useState<Page>("dashboard"),[items,setItems]=useState(seed),[clock,setClock]=useState(new Date()),[notice,setNotice]=useState(""),[menu,setMenu]=useState(false);
 useEffect(()=>{const t=setInterval(()=>setClock(new Date()),1000);return()=>clearInterval(t)},[]);
 useEffect(()=>{fetch("/api/records").then(r=>r.json()).then((d:Item[])=>d.length&&setItems(d)).catch(()=>{})},[]);
 async function save(type:string,data:Record<string,string>){const item:Item={id:Date.now(),type,title:type==="booking"?`STSL-2026-${1048+items.length}`:data.name||data.lr||data.vehicle||"New record",route:data.from&&data.to?`${data.from} → ${data.to}`:data.phone||data.licence||"STSL record",customer:data.customer||data.name||"—",vehicle:data.vehicle||"Unassigned",status:type==="booking"?"Booked":"Active",amount:data.amount||"—"};setItems(x=>[item,...x]);setNotice("Record saved successfully");try{await fetch("/api/records",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(item)})}catch{}}
 if(!login)return <Login clock={clock} name={authenticatedName} go={(e)=>{e.preventDefault();setLogin(true)}}/>;
 return <div className="shell"><aside className={menu?"side open":"side"}><Brand/><nav>{nav.map(n=><button className={page===n.id?"active":""} key={n.id} onClick={()=>{setPage(n.id);setMenu(false)}}><b>{n.icon}</b>{n.label}</button>)}</nav><div className="support"><b>24/7 Operations</b><small>Always moving forward.</small></div><button className="signout" onClick={()=>setLogin(false)}>↪ Sign Out</button></aside><main><header><button className="hamb" onClick={()=>setMenu(!menu)}>☰</button><div><small>OPERATIONS CONTROL</small><h1>{nav.find(n=>n.id===page)?.label}</h1></div><div className="account"><div><b>{clock.toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"})}</b><small>{clock.toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})}</small></div><i>SP</i><span><b>{authenticatedName||"Sanjay Patil"}</b><small>Administrator</small></span></div></header><div className="content">{notice&&<div className="toast">✓ {notice}</div>}{page==="dashboard"&&<Dashboard items={items.filter(x=>x.type==="booking")} go={setPage}/>} {page==="booking"&&<FormPage title="Create New Booking" over="SHIPMENT BOOKING" desc="Register a new consignment and assign transport details." submit="Save Booking" save={d=>save("booking",d)} fields={["Customer Name|customer|Company or customer","Pickup From|from|Origin city","Deliver To|to|Destination city","Pickup Date|date|date","Material|material|Goods description","Vehicle Number|vehicle|MH 12 AB 1234","Estimated Freight|amount|₹ 0.00","Contact Number|phone|10-digit number"]}/>} {page==="lr"&&<FormPage title="Generate New LR" over="LORRY RECEIPT" desc="Create a complete lorry receipt for a shipment." submit="Generate LR" save={d=>save("lr",d)} fields={["LR Number|lr|STSL-2026-","Booking Number|booking|Booking reference","Consignor|customer|Sender name","Consignee|consignee|Receiver name","From|from|Origin city","To|to|Destination city","Packages|packages|No. of packages","Weight (kg)|weight|Total weight","Freight Amount|amount|₹ 0.00","Goods Description|goods|Material details"]}/>} {page==="customers"&&<FormPage title="Customer Data Entry" over="CUSTOMER MASTER" desc="Add and maintain customer contact and billing information." submit="Add Customer" save={d=>save("customer",d)} fields={["Customer / Company Name|name|Full legal name","Mobile Number|phone|10-digit number","Email Address|email|name@company.com","GST Number|gst|GSTIN","Billing Address|address|Complete address","City|city|City","State|state|Maharashtra","PIN Code|pin|6-digit PIN"]}/>} {page==="fleet"&&<Fleet save={save}/>} {page==="tracking"&&<Track items={items.filter(x=>x.type==="booking")}/>}</div></main></div>
}
function Brand(){return <div className="brand"><i>S</i><div><b>SHIVSHAHI</b><small>TRANSPORT & LOGISTICS</small></div></div>}
function Login({clock,name,go}:{clock:Date;name:string|null;go:(e:FormEvent<HTMLFormElement>)=>void}){return <div className="login"><section className="visual"><Brand/><div className="pitch"><small>MOVE WITH CONFIDENCE</small><h1>Every load.<br/>Every mile.<br/><em>Under control.</em></h1><p>One secure workspace for bookings, LR management, customers, fleet and live shipment tracking.</p></div><div className="facts"><b>24/7 <small>Operations</small></b><b>100% <small>Traceable</small></b><b>1 <small>Unified system</small></b></div></section><section className="loginbox"><form onSubmit={go}><div className="live">● LIVE · {clock.toLocaleDateString("en-IN",{day:"2-digit",month:"long",year:"numeric"})} · {clock.toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"})}</div><small>SECURE ACCESS</small><h2>Welcome back</h2><p>Sign in to manage STSL operations.</p><Field spec={`Username|username|${name||"Enter username"}`}/><Field spec="User ID|userId|e.g. STSL-ADMIN-01"/><Field spec="Password|password|Enter your password" password/><div className="remember"><label><input type="checkbox"/> Remember me</label><a>Forgot password?</a></div><button className="primary">Login to Dashboard <b>→</b></button><footer>◉ Your connection is protected and encrypted</footer></form></section></div>}
function Field({spec,password=false}:{spec:string;password?:boolean}){const [label,name,ph]=spec.split("|");return <label className="field"><span>{label}</span><input required name={name} type={password?"password":ph==="date"?"date":"text"} placeholder={ph==="date"?"":ph}/></label>}
function Dashboard({items,go}:{items:Item[];go:(p:Page)=>void}){return <><section className="welcome"><div><small>WEDNESDAY · AUGUST 12</small><h2>Good morning, Sanjay.</h2><p>Here’s what’s moving across your network today.</p></div><button className="primary" onClick={()=>go("booking")}>＋ New Booking</button></section><section className="metrics"><Metric t="Total Bookings" v={items.length||48} x="↑ 12% this month"/><Metric t="In Transit" v={items.filter(x=>x.status==="In Transit").length||12} x="4 arriving today"/><Metric t="Delivered" v={items.filter(x=>x.status==="Delivered").length||34} x="↑ 8% this month"/><Metric t="Revenue" v="₹6.84L" x="↑ 14.2% this month"/></section><section className="dash"><div className="panel shipments"><div className="head"><div><h3>Recent Shipments</h3><p>Latest LR and booking activity</p></div><button onClick={()=>go("tracking")}>View all →</button></div><div className="scroll"><table><thead><tr><th>LR NUMBER</th><th>ROUTE</th><th>CUSTOMER</th><th>VEHICLE</th><th>STATUS</th><th>AMOUNT</th></tr></thead><tbody>{items.slice(0,5).map(x=><tr key={x.id}><td><b>{x.title}</b></td><td>{x.route}</td><td>{x.customer}</td><td>{x.vehicle}</td><td><span className={`pill ${x.status.replace(" ","").toLowerCase()}`}>{x.status}</span></td><td><b>{x.amount}</b></td></tr>)}</tbody></table></div></div><div className="panel fleet"><div className="head"><div><h3>Fleet Overview</h3><p>Live vehicle status</p></div></div><div className="ring"><span><b>24</b><small>Total Vehicles</small></span></div><p>● On Trip <b>12</b></p><p>● Available <b>8</b></p><p>● Maintenance <b>4</b></p></div></section><h3 className="quicktitle">Quick Actions</h3><section className="quick">{[["▤","Generate LR","lr"],["⌖","Track Shipment","tracking"],["♙","Add Customer","customers"],["▰","Add Vehicle","fleet"]].map(x=><button key={x[1]} onClick={()=>go(x[2] as Page)}><b>{x[0]}</b><span>{x[1]}<small>Open and manage</small></span>→</button>)}</section></>}
function Metric({t,v,x}:{t:string;v:string|number;x:string}){return <article><i>▤</i><p>{t}</p><h3>{v}</h3><small>{x}</small></article>}
function FormPage({title,over,desc,submit,fields,save}:{title:string;over:string;desc:string;submit:string;fields:string[];save:(d:Record<string,string>)=>void}){function send(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget;save(Object.fromEntries(new FormData(f).entries()) as Record<string,string>);f.reset()}return <div className="entry"><section className="panel form"><small>{over}</small><h2>{title}</h2><p>{desc}</p><form onSubmit={send}>{fields.map(x=><Field key={x} spec={x}/>)}<div className="actions"><button type="reset">Clear Form</button><button className="primary">{submit} →</button></div></form></section><aside className="panel tip"><i>i</i><h3>Keep records accurate</h3><p>Verify contact, route and vehicle details before saving. Information can be updated later.</p></aside></div>}
function Fleet({save}:{save:(t:string,d:Record<string,string>)=>void}){const [tab,setTab]=useState("driver");return <><div className="tabs"><button className={tab==="driver"?"active":""} onClick={()=>setTab("driver")}>Drivers</button><button className={tab==="vehicle"?"active":""} onClick={()=>setTab("vehicle")}>Lorries / Vehicles</button></div><FormPage title={tab==="driver"?"Driver Data Entry":"Lorry / Vehicle Data Entry"} over="FLEET MASTER" desc="Register and maintain fleet information." submit={tab==="driver"?"Add Driver":"Add Vehicle"} save={d=>save(tab,d)} fields={tab==="driver"?["Driver Name|name|Full name","Mobile Number|phone|10-digit number","Driving Licence|licence|Licence number","Licence Expiry|expiry|date","Address|address|Complete address","Emergency Contact|emergency|Contact number"]:["Vehicle Number|vehicle|MH 12 AB 1234","Vehicle Type|type|Open / Container / Trailer","Capacity (Ton)|capacity|e.g. 15","Owner Name|name|Owner name","Insurance Expiry|insurance|date","Permit Expiry|permit|date"]}/></>}
function Track({items}:{items:Item[]}){const [q,setQ]=useState("");const x=items.find(i=>i.title.toLowerCase().includes(q.toLowerCase()))||(q?undefined:items[0]);return <section className="track"><div className="trackhero"><small>LIVE SHIPMENT STATUS</small><h2>Track any consignment</h2><p>Enter an LR number to see its current status and movement.</p><div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Enter LR number, e.g. STSL-2026-1048"/><button className="primary">Track LR</button></div></div>{x?<div className="panel trackcard"><div className="trackhead"><span><small>LR NUMBER</small><h3>{x.title}</h3><p>{x.customer}</p></span><b className="pill intransit">{x.status}</b></div><div className="route"><span><b>{x.route.split(" → ")[0]}</b><small>Picked up</small></span><i/><span><b>{x.route.split(" → ")[1]}</b><small>Destination</small></span></div><div className="details"><span><small>VEHICLE</small><b>{x.vehicle}</b></span><span><small>DRIVER</small><b>To be assigned</b></span><span><small>LAST UPDATE</small><b>Today, 10:42 AM</b></span><span><small>EXPECTED DELIVERY</small><b>13 Aug 2026</b></span></div></div>:<div className="panel empty">No LR found. Check the number and try again.</div>}</section>}
